platform:ios, '7.0'
pod 'SDWebImage', '~> 3.7.5'
pod 'AFNetworking', '~> 2.5.4'
#键盘控制
pod 'IQKeyboardManager', '~> 3.3.4'
#底部弹出
pod 'LCActionSheet', '~> 1.2.0'
#tabbar
pod 'CYLTabBarController', '~> 1.5.6'     #TabBar1.2.1
pod 'MJRefresh', '~> 3.1.0'
#pod 'SVProgressHUD', '~> 2.0.3'
pod 'MBProgressHUD', '~> 1.0.0'

#滑动返回
pod 'FDFullscreenPopGesture', '1.1'

#动画
pod 'pop', '~> 1.0.9'
#解析xml
pod 'XMLDictionary', '~> 1.4'
#pod 'FCUUID'

#地图
#pod 'AMap2DMap' #2D地图SDK(2D地图和3D地图不能同时使用)
pod 'AMapNavi', '~> 2.2.0'                #导航SDK
pod 'AMapLocation', '~> 2.1.1'            #定位SDK
pod 'AMapSearch', '~> 4.2.0'              #搜索服务SDK

#Bugly 错误日志
pod 'Bugly', '~> 2.4.0'
